// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWyL-GkMAxv1sgY2rYz9j_XscOuqIEP9U',
    appId: '1:157310866846:web:e5149e1e21df518da5728f',
    messagingSenderId: '157310866846',
    projectId: 'resume-52ac7',
    authDomain: 'resume-52ac7.firebaseapp.com',
    storageBucket: 'resume-52ac7.appspot.com',
    measurementId: 'G-0QL7ME77R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_7VtFJgqgXUpmnB9swVIARao0eSRx8A',
    appId: '1:157310866846:android:19bc98989eb73281a5728f',
    messagingSenderId: '157310866846',
    projectId: 'resume-52ac7',
    storageBucket: 'resume-52ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_E6rZKHyA2KP5WIjPC7N0_dAj7aPVVIs',
    appId: '1:157310866846:ios:36b611bedc27fbafa5728f',
    messagingSenderId: '157310866846',
    projectId: 'resume-52ac7',
    storageBucket: 'resume-52ac7.appspot.com',
    iosBundleId: 'com.example.resumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_E6rZKHyA2KP5WIjPC7N0_dAj7aPVVIs',
    appId: '1:157310866846:ios:36b611bedc27fbafa5728f',
    messagingSenderId: '157310866846',
    projectId: 'resume-52ac7',
    storageBucket: 'resume-52ac7.appspot.com',
    iosBundleId: 'com.example.resumeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWyL-GkMAxv1sgY2rYz9j_XscOuqIEP9U',
    appId: '1:157310866846:web:d01afd68203885cfa5728f',
    messagingSenderId: '157310866846',
    projectId: 'resume-52ac7',
    authDomain: 'resume-52ac7.firebaseapp.com',
    storageBucket: 'resume-52ac7.appspot.com',
    measurementId: 'G-RP24HZQ1WV',
  );
}
